[usecli]
title = "useChange"
title_file = "themes/title.txt"
title_font = "ansi_shadow"
description = "Automated python change and release"
commands_dir = "commands"
templates_dir = "templates"
themes_dir = "themes"
theme = "default"
hide_init = true
hide_inspire = true
hide_make_command = true
hide_make_theme = true
