[usecli]
command_name = "usechange"
title = "useChange"
title_file = "cli/themes/title.txt"
title_font = "ansi_shadow"
description = "Generate Beautiful Changelogs using Conventional Commits"
commands_dir = "cli/commands"
templates_dir = "cli/templates"
themes_dir = "cli/themes"
theme = "default"
hide_init = true
hide_inspire = true
hide_make_command = true
hide_make_theme = true
